#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ec2-ap-southeast-1:Chrome?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ec2-ap-southeast-2:Chrome?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ec2-eu-central-1:Chrome Canary?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ec2-eu-west-3:Firefox Nightly?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ec2-us-west-1:Brave?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ec2-us-east-1:Brave?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ap-south-1:Chrome?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/Dulles_MotoG4:Moto G4 - Opera Mini (High)?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ec2-sa-east-1:Brave?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ec2-sa-east-1:Chrome?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/Dulles_IE11?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/Dulles_iPad?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/Dulles_MotoG:Motorola G - Chrome?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/Dulles:Chrome|kainy.cn|Cable?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/Dulles:Chrome|kainy.cn|LTE?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ec2-ap-northeast-1:Chrome?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ec2-ap-northeast-2:Chrome?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/ec2-eu-west-1:Chrome?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/Dulles_MotoG:Moto G - UC Browser?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/London_EC2?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/guotao/speedtracker2/master/Dulles:Chrome?key=guotao' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/iffe-team/speedtracker/master/default?key=iffe' 
curl --write-out '%{http_code} %{time_starttransfer} \n%{url_effective}\n' -o /dev/null -sS 'https://admin.leanapp.cn/v1/test/iffe-team/speedtracker/master/ttyl?key=iffe' 
echo "----------------------------------------------------------------------------"
endDate=`date +"%Y-%m-%d %H:%M:%S"`
echo "[$endDate] Successful , trigged by: https://cron-job.org"
echo "----------------------------------------------------------------------------"
